language: cpp
os:
  - osx
  - linux
env:
  - NODE_VERSION="0.10"
    JULIA_VERSION="0.3"
  - NODE_VERSION="0.12"
    JULIA_VERSION="0.4"
  - NODE_VERSION="0.12"
    JULIA_VERSION="0.5"
  - NODE_VERSION="4.2.3"
    JULIA_VERSION="0.4"
  - NODE_VERSION="4.2"
    JULIA_VERSION="0.5"
  - NODE_VERSION="5.1"
    JULIA_VERSION="0.4"
  - NODE_VERSION="5.1"
    JULIA_VERSION="0.5"
before_install:
  - if [ `uname` = "Darwin" ]; then
      brew uninstall nvm;
    fi
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - if [ `uname` = "Linux" ]; then
      sudo add-apt-repository ppa:staticfloat/julia-deps -y;
      if [ "$JULIA_VERSION" = "0.3" ]; then
         sudo add-apt-repository ppa:staticfloat/juliareleases -y;
         sudo apt-get update -qq -y;
         sudo apt-get install libpcre3-dev julia0.3 -y;
      elif [ "$JULIA_VERSION" = "0.4" ]; then
         sudo add-apt-repository ppa:staticfloat/juliareleases -y;
         sudo apt-get update -qq -y;
         sudo apt-get install libpcre3-dev julia -y;
      else
         sudo add-apt-repository ppa:staticfloat/julianightlies -y;
         sudo apt-get update -qq -y;
         sudo apt-get install libpcre3-dev julia -y;
      fi;
      export CXX="g++-4.8";
      npm install -g mocha chai sinon bindings node-gyp;
    elif [ `uname` = "Darwin" ]; then
      npm install -g mocha chai sinon bindings node-gyp;
      if [ "$JULIA_VERSION" = "0.3" ]; then
        wget -O julia.dmg "https://s3.amazonaws.com/julialang/bin/osx/x64/0.3/julia-0.3.12-osx10.7+.dmg";
      elif [ "$JULIA_VERSION" = "0.4" ]; then
        wget -O julia.dmg "http://status.julialang.org/stable/osx10.7+";
      else
        wget -O julia.dmg "http://status.julialang.org/download/osx10.7+";
      fi;
      hdiutil mount julia.dmg;
      cp -Ra /Volumes/Julia/*.app/Contents/Resources/julia ~;
      export PATH=$PATH:~/julia/bin;
    fi
  - node --version
  - julia -e 'versioninfo()'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm install
  - npm test
